[tool.poetry]
name = "lobotomy"
version = "0.1.0"
description = ""
authors = ["Scott Ernst <swernst@gmail.com>"]
exclude = ["lobotomy/tests"]

[tool.poetry.dependencies]
python = "^3.8.1"
boto3 = "^1.16.0"
toml = "^0.10.1"
PyYAML = "^5.3.1"
python-dateutil = "^2.8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
coverage = "^5.3"

[tool.poetry.scripts]
lobotomy = 'lobotomy:run_cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
