name: lint
on: [push]
jobs:
  black:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - run: ls -la
      - run: pip install poetry
      - run: poetry install
      - run: black --check .
  pytest:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - run: ls -la
      - run: pip install poetry
      - run: poetry install
      - run: pytest --cov-report=term-missing  --cov=lobotomy .
