name: lint
on: [push]
jobs:
#  black:
#    runs-on: ubuntu-latest
#    container: python:3
#    steps:
#      - run: ls -la /__w
#      - run: ls -la /__w/lobotomy
#      - run: pip install poetry
#      - run: poetry install
#      - run: black --check .
  pytest:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - run: ls -la ~
      - run: ls -la /github/home
      - run: ls -la /github/workflow
      - run: pip install poetry
      - run: poetry install
      - run: pytest --cov-report=term-missing  --cov=lobotomy .
