name: validation
on: [push]
jobs:
  black:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: pip install poetry
      - run: poetry install
      - run: black --check .
  pytest:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: pip install poetry
      - run: poetry install
      - run: pytest --cov-report=term-missing  --cov=lobotomy .
